### ISSUE TITLE
koalarization.dataset.lab_batch issue

### ISSUE THREAD

**Issue by lucasSaavedra123** [baldassarreFe/deep-koalarization#23]
Hi! I want to run 

`python -m koalarization.dataset.lab_batch -c '../data/inception_resnet_v2_2016_08_30.ckpt' '../data/resized' '../data/tfrecords' --verbose`

I have the following Traceback:

```
Using TensorFlow backend.
2021-12-01 00:26:43.453183: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2021-12-01 00:27:03.174050: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2021-12-01 00:27:03.174278: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2021-12-01 00:27:03.174446: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2021-12-01 00:27:03.174590: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Finished writing 0 images in 0.54s
Traceback (most recent call last):
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/Lucas Ariel Saavedra/Documents/GitHub/deep-koalarization/src/koalarization/dataset/lab_batch.py", line 255, in <module>
    ).batch_all(examples_per_record=args.batch_size)
  File "/mnt/c/Users/Lucas Ariel Saavedra/Documents/GitHub/deep-koalarization/src/koalarization/dataset/lab_batch.py", line 89, in batch_all
    self._run_session(sess, operations, examples_per_record)
  File "/mnt/c/Users/Lucas Ariel Saavedra/Documents/GitHub/deep-koalarization/src/koalarization/dataset/lab_batch.py", line 172, in _run_session
    coord.join(threads)
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/lucas/anaconda3/envs/koalarization/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [string_input_producer requires a non-null input tensor]
         [[Node: input_producer/Assert/Assert = Assert[T=[DT_STRING], summarize=3, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/Greater, input_producer/Assert/Assert/data_0)]]
```

I don't know how to fix it. Thank You!

PD: I'm working without GPU

**Comment by lucasSaavedra123** [comment]
https://github.com/GoogleCloudPlatform/training-data-analyst/issues/281#issuecomment-424753678

Seeing this issue it seems to be that is not reading images that I have in `data`. This is weird.

**Comment by lucasSaavedra123** [comment]
https://github.com/ghwatson/faststyle/issues/3#issuecomment-299067594

Another issue related to this. I tried with and without `/` in directories path input but nothing worked.

**Comment by lucasSaavedra123** [comment]
Maybe the first messages are the reason why this is not working. I'm going to make a little research on this. If I receive a early solution I will appreciate it.

**Comment by lucasSaavedra123** [comment]
I tried with

`python -m koalarization.dataset.lab_batch -c 'data/inception_resnet_v2_2016_08_30.ckpt' 'data/resized' 'data/tfrecords'
`

but It doesn't work.

**Comment by dofranko** [comment]
Hi @lucasSaavedra123,
problem is probably in line 
```file_matcher = tf.train.match_filenames_once(join(folder, "*.jpeg"))```.

Change .jpeg to .jpg if your files have that extension
